In [2]:
import numpy as np

##### 1) Write a program to create a 5 dimensional array with all zeros and ones


In [25]:
arr_zero = np.zeros((3,3,3,3,3))
print(arr_zero)
print(arr_zero.ndim)

arr_ones = np.ones((1,1,1,1,1))
print(arr_ones)
print(arr_ones.ndim)

[[[[[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]]


  [[[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]]


  [[[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]]]



 [[[[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]]


  [[[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]]


  [[[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]]]



 [[[[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]

###### 2)Write a program to create an array of 10 zeros,10 ones, and 10 fives in row 1 2 and 3 which create a new array of shape (3,10)


In [21]:
a = [[0,0,0,0,0,0,0,0,0,0],[1,1,1,1,1,1,1,1,1,1],[5,5,5,5,5,5,5,5,5,5]]
np.shape(a)

np.reshape(a,(3,10))

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])

In [19]:
x= np.array([np.zeros(10),np.ones(10),np.full(10,5)])
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])

###### 3) Write a program to create a 3x4 matrix filled with values from 10 to 21.

In [3]:
matrix_3_4 = np.arange(10,22).reshape(3,4)
matrix_3_4

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])


###### 4) Write a program to create a 10x10 zero matrix with elements on the main diagonal equal to 0,1,2,3,4,5,6,7,8,9,



In [5]:
matrix = np.zeros((10, 10), dtype=int)
matrix[np.arange(10), np.arange(10)] = np.arange(10)
print(matrix)

[[0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 2 0 0 0 0 0 0 0]
 [0 0 0 3 0 0 0 0 0 0]
 [0 0 0 0 4 0 0 0 0 0]
 [0 0 0 0 0 5 0 0 0 0]
 [0 0 0 0 0 0 6 0 0 0]
 [0 0 0 0 0 0 0 7 0 0]
 [0 0 0 0 0 0 0 0 8 0]
 [0 0 0 0 0 0 0 0 0 9]]


###### 5) Write a program to create a 4x4 array. Create an array from below array by swapping first and last, second and third columns.

In [6]:
array = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])
array[:, [0, -1]] = array[:, [-1, 0]]
array[:, [1, 2]] = array[:, [2, 1]]
print(array)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


###### 6) Write a program to reverse an array (the first element becomes the last).
Given array:[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 ]

In [8]:
arr_2 = np.arange(12,28)
print(arr_2)
arr_2[::-1]


[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27]


array([27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12])

###### 7) Write a program to access all the elements greater than 30 and less than 80 and multiples of 5 from an array of shape 10,10 .Elements range from 1 to 100

In [9]:
arr_3 = np.arange(1,101).reshape(10,10)
arr_3
mul = arr_3[np.where((arr_3 > 30) & (arr_3 < 80) & (arr_3 % 5 == 0))]
print(mul)

[35 40 45 50 55 60 65 70 75]


##### 8) Write a program to create a 2D array with 1 on the border and 0 inside.

In [12]:
x = np.ones((5,5),dtype = int)
x


array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [15]:
x[1:-1,1:-1] = 0
print(x)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


###### 9) Write a program to create a checkerboard pattern .Don't use default array function

In [18]:
a = np.ones((8,8),dtype=int)
a
a[::2, ::2] = 0
a[1::2, 1::2] = 0
a[::2, 1::2] = 1
a[1::2, ::2] = 1
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


##### 10) Write a program to find common values between two arrays.

In [19]:
array1 = [4,9,6,1,3,4,7,3]
array2 = [8,7,3,2,1,1,4,2]
    
common = np.intersect1d(array1,array2)
common

array([1, 3, 4, 7])

###### 11) Write a program to create an array 2d array and then reshape into 1d array

In [21]:
x = np.arange(1,11).reshape(2,5)
x
y = x.reshape(-1)
y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])