In [28]:
import numpy as np

In [34]:
file ='tipsf.csv'

In [35]:
x = np.genfromtxt(file,delimiter=',',skip_header=True)
x

array([[  0.  ,  16.99,   1.01, ...,   1.  ,   0.  ,   2.  ],
       [  1.  ,  10.34,   1.66, ...,   1.  ,   0.  ,   3.  ],
       [  2.  ,  21.01,   3.5 , ...,   1.  ,   0.  ,   3.  ],
       ...,
       [241.  ,  22.67,   2.  , ...,   0.  ,   0.  ,   2.  ],
       [242.  ,  17.82,   1.75, ...,   0.  ,   0.  ,   2.  ],
       [243.  ,  18.78,   3.  , ...,   2.  ,   0.  ,   2.  ]])

###### 1)What is the total bill value?

In [4]:
sum_total_bill =np.sum(x[:,1])
print(x)
print(sum_total_bill)

[[  0.    16.99   1.01 ...   1.     0.     2.  ]
 [  1.    10.34   1.66 ...   1.     0.     3.  ]
 [  2.    21.01   3.5  ...   1.     0.     3.  ]
 ...
 [241.    22.67   2.   ...   0.     0.     2.  ]
 [242.    17.82   1.75 ...   0.     0.     2.  ]
 [243.    18.78   3.   ...   2.     0.     2.  ]]
4827.77


###### 2)What is total tip value.

In [5]:
sum_tip_vaue = np.sum(x[:,2])
print(x)
print(sum_tip_vaue)

[[  0.    16.99   1.01 ...   1.     0.     2.  ]
 [  1.    10.34   1.66 ...   1.     0.     3.  ]
 [  2.    21.01   3.5  ...   1.     0.     3.  ]
 ...
 [241.    22.67   2.   ...   0.     0.     2.  ]
 [242.    17.82   1.75 ...   0.     0.     2.  ]
 [243.    18.78   3.   ...   2.     0.     2.  ]]
731.5799999999999


###### 3)Count how many sun,sat,thur,friday are there.

In [6]:
np.unique(x[:,5])

array([0., 1., 2., 3.])

In [7]:
np.unique(x[:,5],return_counts=True)

(array([0., 1., 2., 3.]), array([87, 76, 62, 19], dtype=int64))

###### 4)How many smokers are there?


In [8]:
np.unique(x[:,4])

array([0., 1.])

In [9]:
y=np.unique(x[:,4],return_counts=True)
print(y)
z=np.sum(x[:,4])
print(z)

(array([0., 1.]), array([151,  93], dtype=int64))
93.0


###### 5)What is the average tip given by female and male

In [10]:
gen =(x[:,3])
tip=(x[:,2])
total_tip_male = np.mean(tip[gen==0])
total_tip_fem = np.mean(tip[gen==1])
print(total_tip_male)
print(total_tip_fem)

2.8334482758620685
3.0896178343949043


###### 6)How much amount have been spent by male and female

In [11]:
gen =(x[:,3])
total_bill=(x[:,1])
tip =(x[:,2])
tip_male = np.sum(tip[gen==0])
tip_female =np.sum(tip[gen==1])
amt_male = np.sum(total_bill[gen==0])
amt_female = np.sum(total_bill[gen==1])
total_male = tip_male + amt_male
total_female = tip_female + amt_female
print(total_male)
print(total_female)


1817.4599999999996
3741.89


###### 7) What is the min and max tip given.

In [15]:
tip=x[:,2]
min_tip = np.min(tip)
print(min_tip)
max_tip = np.max(tip)
print(max_tip)

1.0
10.0


###### 8)How many males and female are going for dinner and lunch.

In [19]:
gender = x[:,3]
time = x[:,6]
male_lunch = np.sum((gender == 0) & (time == 1))
female_lunch = np.sum((gender == 1) & (time == 1))
male_lunch = np.sum((gender == 0) & (time == 0))
female_lunch = np.sum((gender == 1) & (time == 0))
print("No of males went for lunch:", male_lunch )
print("No of females went for lunch:",female_lunch)
print("No of males went for Dinner:", male_lunch )
print("No of female went for Dinner:",female_lunch)

No of males went for lunch: 52
No of females went for lunch: 124
No of males went for Dinner: 52
No of female went for Dinner: 124


###### 9) find out the average size.

In [36]:
size = x[:, 7]
np.mean(size)

2.569672131147541

###### 10)How many female and male smokers are there.


In [31]:
smoker = x[:, 4]
gender = x[:, 3]
x= np.sum((gender == 0) & (smoker == 1))
y = np.sum((gender == 1) & (smoker == 1))
print("No of male smokers:", x)
print("No of female smokers:", y)

No of male smokers: 33
No of female smokers: 60
